strictness: low
test-warnings: true
doc-warnings: false

pylint:
  disable:
    - super-init-not-called
    - unsubscriptable-object
    - too-many-arguments
    - bare-except
    - line-too-long
    - import-outside-toplevel
    - missing-timeout
    - too-many-nested-blocks
    - unpacking-non-sequence
    - not-an-iterable
    - consider-using-f-string

pycodestyle:
  disable:
    - E722
    - E501

mccabe:
  disable:
    - MC0001
  run: true
