strictness: high
test-warnings: true
doc-warnings: false

pylint:
  disable:
    - super-init-not-called
    - unsubscriptable-object
    - too-many-arguments
    - bare-except

pycodestyle:
  disable:
    - E722

mccabe:
  disable:
    - MC0001
  run: true