version: '3'

services:
  backend:
    container_name: depex_backend
    build: .
    depends_on:
      - database
      - database_seeder
    ports:
      - '8000:8000'
    networks:
      - depex

  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - depex

  database_seeder:
    container_name: mongodb_seeder
    image: mongo:latest
    links:
      - database
    volumes:
      - ./mongo_seed:/mongo_seed
    command:
      /mongo_seed/import.sh
    networks:
      - depex

networks:
  depex:
    driver: bridge

volumes:
  data: